Add build option to explicitly specify BLAS/LAPACK
lanl/bml pull request #321
Opened 2019-12-05 20:13 UTC by jeanlucf22

Will use environment variables BLAS_LIBRARIES and
LAPACK_LIBRARIES if defined to specify where those libraries are.

2019-12-05 20:52 UTC, suemni approved these changes
Sounds good!

2019-12-06 13:21 UTC, nicolasbock requested changes
Thanks, looks great! Just one small spelling suggestion.

2019-12-06 13:21 UTC, nicolasbock commented on CMakeLists.txt
> +  message(STATUS "I will rely on the default paths or enironment variables to find BLAS/LAPACK")
```suggestion
  message(STATUS "I will rely on the default paths or environment variables to find BLAS/LAPACK")
```

2019-12-09 13:40 UTC, nicolasbock approved these changes
Thanks for fixing!

2019-12-09 13:41 UTC, merged