added sparse matrix example
lanl/bml pull request #534
Opened 2021-07-25 20:50 UTC by finkeljos

Added a .c file to /bml/examples/sparse-matrix/ that generates a sparse Hamiltonian matrix using the example Hamiltonian shown in https://doi.org/10.1021/acs.jctc.1c00057

2021-07-26 02:35 UTC, cnegre approved these changes

2021-07-26 02:36 UTC, cnegre commented
@finkeljos Try to fix the indentation with the indent.sh script

2021-07-26 08:06 UTC, nicolasbock requested changes
As @cnegre already said, indentation is incorrect.

2021-07-26 13:39 UTC, jeanlucf22 requested changes
The header line for the matrix market format seems to be missing in the created file. I am not sure it is always required, but it is good practice to have a short description of the type of matrix in the file

2021-07-28 01:05 UTC, jeanlucf22 approved these changes

2021-07-28 16:58 UTC, nicolasbock approved these changes

2021-07-28 16:58 UTC, merged