Updated manual
lanl/bml pull request #662
Opened 2022-09-28 16:30 UTC by cnegre

Updating manual

2022-09-28 16:37 UTC, suemni approved these changes

2022-09-28 16:53 UTC, jeanlucf22 requested changes
Why is this pdf in the repo? Isn't it a "generated" file? As such, I would keep only the source files in the repo, not the generated pdf.

2022-09-28 17:37 UTC, nicolasbock commented
We should provide this pdf as an artifact of a release. @cnegre Can you remove the pdf from this PR? I will follow up with another one that publishes the pdf for a release.

2022-10-04 18:10 UTC, nicolasbock requested changes
Please remove the `pdf` file from the repository in this PR @cnegre

2022-10-05 03:14 UTC, closed without merging